title: EloNet
baseURL: /
params:
  footer:
    content: '&copy; EloNet. All rights reserved.'
    has_nav: false
    has_social: false
    has_subscribe: false
    links: []
    logo_img: ''
    nav_title: Company
    social_title: Community
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: ''
  header:
    has_nav: true
    logo_img: /images/elonet.png
    title: EloNet
    menu:
      actions:
        - label: Sign Up
          url: /signup
  palette: blue
disableKinds:
  - RSS
